//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerApp.Website.TimelogSecurity {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APIBase", Namespace="http://schemas.datacontract.org/2004/07/TimeLog.TLP.API.Proxy.Communication.V1_1")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TrackerApp.Website.TimelogSecurity.SecurityToken))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TrackerApp.Website.TimelogSecurity.TimeRegistrationSettings))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TrackerApp.Website.TimelogSecurity.User))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TrackerApp.Website.TimelogSecurity.Request))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TrackerApp.Website.TimelogSecurity.ResponseOfTimeRegistrationSettings))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TrackerApp.Website.TimelogSecurity.ResponseOfUser))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TrackerApp.Website.TimelogSecurity.ResponseOfSecurityToken))]
    public partial class APIBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecurityToken", Namespace="http://www.timelog.com/api/tlp/v1_2")]
    [System.SerializableAttribute()]
    public partial class SecurityToken : TrackerApp.Website.TimelogSecurity.APIBase {
        
        private string InitialsField;
        
        private System.DateTime ExpiresField;
        
        private string HashField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Initials {
            get {
                return this.InitialsField;
            }
            set {
                if ((object.ReferenceEquals(this.InitialsField, value) != true)) {
                    this.InitialsField = value;
                    this.RaisePropertyChanged("Initials");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime Expires {
            get {
                return this.ExpiresField;
            }
            set {
                if ((this.ExpiresField.Equals(value) != true)) {
                    this.ExpiresField = value;
                    this.RaisePropertyChanged("Expires");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string Hash {
            get {
                return this.HashField;
            }
            set {
                if ((object.ReferenceEquals(this.HashField, value) != true)) {
                    this.HashField = value;
                    this.RaisePropertyChanged("Hash");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimeRegistrationSettings", Namespace="http://www.timelog.com/api/tlp/v1_2")]
    [System.SerializableAttribute()]
    public partial class TimeRegistrationSettings : TrackerApp.Website.TimelogSecurity.APIBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool UseCaseSensetiveLoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool UseWBSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool UseTaskUniqueIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CustomerSortByNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ProjectSortByNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FormatingLCIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool UseStartEndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TimeTrackingShowCustomerNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TimeTrackingShowCustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TimeTrackingShowProjectNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TimeTrackingShowWBSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TimeTrackingShowTaskIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AllowTimetrackingOnAllActiveProjectsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TimeTrackingAllowRegistrationOverlapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ShowTimesheetAdditionalTextFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdditionalTextFieldLabelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AdditionalTextFieldValidationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AdditionalTextFieldTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UseCaseSensetiveLogin {
            get {
                return this.UseCaseSensetiveLoginField;
            }
            set {
                if ((this.UseCaseSensetiveLoginField.Equals(value) != true)) {
                    this.UseCaseSensetiveLoginField = value;
                    this.RaisePropertyChanged("UseCaseSensetiveLogin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UseWBS {
            get {
                return this.UseWBSField;
            }
            set {
                if ((this.UseWBSField.Equals(value) != true)) {
                    this.UseWBSField = value;
                    this.RaisePropertyChanged("UseWBS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool UseTaskUniqueID {
            get {
                return this.UseTaskUniqueIDField;
            }
            set {
                if ((this.UseTaskUniqueIDField.Equals(value) != true)) {
                    this.UseTaskUniqueIDField = value;
                    this.RaisePropertyChanged("UseTaskUniqueID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool CustomerSortByNo {
            get {
                return this.CustomerSortByNoField;
            }
            set {
                if ((this.CustomerSortByNoField.Equals(value) != true)) {
                    this.CustomerSortByNoField = value;
                    this.RaisePropertyChanged("CustomerSortByNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool ProjectSortByNo {
            get {
                return this.ProjectSortByNoField;
            }
            set {
                if ((this.ProjectSortByNoField.Equals(value) != true)) {
                    this.ProjectSortByNoField = value;
                    this.RaisePropertyChanged("ProjectSortByNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int FormatingLCID {
            get {
                return this.FormatingLCIDField;
            }
            set {
                if ((this.FormatingLCIDField.Equals(value) != true)) {
                    this.FormatingLCIDField = value;
                    this.RaisePropertyChanged("FormatingLCID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool UseStartEndTime {
            get {
                return this.UseStartEndTimeField;
            }
            set {
                if ((this.UseStartEndTimeField.Equals(value) != true)) {
                    this.UseStartEndTimeField = value;
                    this.RaisePropertyChanged("UseStartEndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public bool TimeTrackingShowCustomerNo {
            get {
                return this.TimeTrackingShowCustomerNoField;
            }
            set {
                if ((this.TimeTrackingShowCustomerNoField.Equals(value) != true)) {
                    this.TimeTrackingShowCustomerNoField = value;
                    this.RaisePropertyChanged("TimeTrackingShowCustomerNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public bool TimeTrackingShowCustomerName {
            get {
                return this.TimeTrackingShowCustomerNameField;
            }
            set {
                if ((this.TimeTrackingShowCustomerNameField.Equals(value) != true)) {
                    this.TimeTrackingShowCustomerNameField = value;
                    this.RaisePropertyChanged("TimeTrackingShowCustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public bool TimeTrackingShowProjectNo {
            get {
                return this.TimeTrackingShowProjectNoField;
            }
            set {
                if ((this.TimeTrackingShowProjectNoField.Equals(value) != true)) {
                    this.TimeTrackingShowProjectNoField = value;
                    this.RaisePropertyChanged("TimeTrackingShowProjectNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public bool TimeTrackingShowWBS {
            get {
                return this.TimeTrackingShowWBSField;
            }
            set {
                if ((this.TimeTrackingShowWBSField.Equals(value) != true)) {
                    this.TimeTrackingShowWBSField = value;
                    this.RaisePropertyChanged("TimeTrackingShowWBS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public bool TimeTrackingShowTaskID {
            get {
                return this.TimeTrackingShowTaskIDField;
            }
            set {
                if ((this.TimeTrackingShowTaskIDField.Equals(value) != true)) {
                    this.TimeTrackingShowTaskIDField = value;
                    this.RaisePropertyChanged("TimeTrackingShowTaskID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public bool AllowTimetrackingOnAllActiveProjects {
            get {
                return this.AllowTimetrackingOnAllActiveProjectsField;
            }
            set {
                if ((this.AllowTimetrackingOnAllActiveProjectsField.Equals(value) != true)) {
                    this.AllowTimetrackingOnAllActiveProjectsField = value;
                    this.RaisePropertyChanged("AllowTimetrackingOnAllActiveProjects");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public bool TimeTrackingAllowRegistrationOverlap {
            get {
                return this.TimeTrackingAllowRegistrationOverlapField;
            }
            set {
                if ((this.TimeTrackingAllowRegistrationOverlapField.Equals(value) != true)) {
                    this.TimeTrackingAllowRegistrationOverlapField = value;
                    this.RaisePropertyChanged("TimeTrackingAllowRegistrationOverlap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public bool ShowTimesheetAdditionalTextField {
            get {
                return this.ShowTimesheetAdditionalTextFieldField;
            }
            set {
                if ((this.ShowTimesheetAdditionalTextFieldField.Equals(value) != true)) {
                    this.ShowTimesheetAdditionalTextFieldField = value;
                    this.RaisePropertyChanged("ShowTimesheetAdditionalTextField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public string AdditionalTextFieldLabel {
            get {
                return this.AdditionalTextFieldLabelField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalTextFieldLabelField, value) != true)) {
                    this.AdditionalTextFieldLabelField = value;
                    this.RaisePropertyChanged("AdditionalTextFieldLabel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public int AdditionalTextFieldValidation {
            get {
                return this.AdditionalTextFieldValidationField;
            }
            set {
                if ((this.AdditionalTextFieldValidationField.Equals(value) != true)) {
                    this.AdditionalTextFieldValidationField = value;
                    this.RaisePropertyChanged("AdditionalTextFieldValidation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public int AdditionalTextFieldType {
            get {
                return this.AdditionalTextFieldTypeField;
            }
            set {
                if ((this.AdditionalTextFieldTypeField.Equals(value) != true)) {
                    this.AdditionalTextFieldTypeField = value;
                    this.RaisePropertyChanged("AdditionalTextFieldType");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://www.timelog.com/api/tlp/v1_2")]
    [System.SerializableAttribute()]
    public partial class User : TrackerApp.Website.TimelogSecurity.APIBase {
        
        private int IDField;
        
        private string InitialsField;
        
        private string FirstNameField;
        
        private string LastNameField;
        
        private int LanguageIDField;
        
        private TrackerApp.Website.TimelogSecurity.Role[] RolesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Initials {
            get {
                return this.InitialsField;
            }
            set {
                if ((object.ReferenceEquals(this.InitialsField, value) != true)) {
                    this.InitialsField = value;
                    this.RaisePropertyChanged("Initials");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int LanguageID {
            get {
                return this.LanguageIDField;
            }
            set {
                if ((this.LanguageIDField.Equals(value) != true)) {
                    this.LanguageIDField = value;
                    this.RaisePropertyChanged("LanguageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public TrackerApp.Website.TimelogSecurity.Role[] Roles {
            get {
                return this.RolesField;
            }
            set {
                if ((object.ReferenceEquals(this.RolesField, value) != true)) {
                    this.RolesField = value;
                    this.RaisePropertyChanged("Roles");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Request", Namespace="http://www.timelog.com/api/tlp/v1_1")]
    [System.SerializableAttribute()]
    public partial class Request : TrackerApp.Website.TimelogSecurity.APIBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TrackerApp.Website.TimelogSecurity.RequestParameter[] ParametersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MethodNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackerApp.Website.TimelogSecurity.RequestParameter[] Parameters {
            get {
                return this.ParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.ParametersField, value) != true)) {
                    this.ParametersField = value;
                    this.RaisePropertyChanged("Parameters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceClass {
            get {
                return this.ServiceClassField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceClassField, value) != true)) {
                    this.ServiceClassField = value;
                    this.RaisePropertyChanged("ServiceClass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string MethodName {
            get {
                return this.MethodNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MethodNameField, value) != true)) {
                    this.MethodNameField = value;
                    this.RaisePropertyChanged("MethodName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfTimeRegistrationSettings", Namespace="http://www.timelog.com/api/tlp/v1_1")]
    [System.SerializableAttribute()]
    public partial class ResponseOfTimeRegistrationSettings : TrackerApp.Website.TimelogSecurity.APIBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TrackerApp.Website.TimelogSecurity.TimeRegistrationSettings[] ReturnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnTypeDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TrackerApp.Website.TimelogSecurity.Request RequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TrackerApp.Website.TimelogSecurity.ExecutionStatus ResponseStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TrackerApp.Website.TimelogSecurity.APIMessage[] MessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackerApp.Website.TimelogSecurity.TimeRegistrationSettings[] Return {
            get {
                return this.ReturnField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnField, value) != true)) {
                    this.ReturnField = value;
                    this.RaisePropertyChanged("Return");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnTypeDescription {
            get {
                return this.ReturnTypeDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnTypeDescriptionField, value) != true)) {
                    this.ReturnTypeDescriptionField = value;
                    this.RaisePropertyChanged("ReturnTypeDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public TrackerApp.Website.TimelogSecurity.Request Request {
            get {
                return this.RequestField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestField, value) != true)) {
                    this.RequestField = value;
                    this.RaisePropertyChanged("Request");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public TrackerApp.Website.TimelogSecurity.ExecutionStatus ResponseState {
            get {
                return this.ResponseStateField;
            }
            set {
                if ((this.ResponseStateField.Equals(value) != true)) {
                    this.ResponseStateField = value;
                    this.RaisePropertyChanged("ResponseState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public TrackerApp.Website.TimelogSecurity.APIMessage[] Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfUser", Namespace="http://www.timelog.com/api/tlp/v1_1")]
    [System.SerializableAttribute()]
    public partial class ResponseOfUser : TrackerApp.Website.TimelogSecurity.APIBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TrackerApp.Website.TimelogSecurity.User[] ReturnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnTypeDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TrackerApp.Website.TimelogSecurity.Request RequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TrackerApp.Website.TimelogSecurity.ExecutionStatus ResponseStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TrackerApp.Website.TimelogSecurity.APIMessage[] MessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackerApp.Website.TimelogSecurity.User[] Return {
            get {
                return this.ReturnField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnField, value) != true)) {
                    this.ReturnField = value;
                    this.RaisePropertyChanged("Return");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnTypeDescription {
            get {
                return this.ReturnTypeDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnTypeDescriptionField, value) != true)) {
                    this.ReturnTypeDescriptionField = value;
                    this.RaisePropertyChanged("ReturnTypeDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public TrackerApp.Website.TimelogSecurity.Request Request {
            get {
                return this.RequestField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestField, value) != true)) {
                    this.RequestField = value;
                    this.RaisePropertyChanged("Request");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public TrackerApp.Website.TimelogSecurity.ExecutionStatus ResponseState {
            get {
                return this.ResponseStateField;
            }
            set {
                if ((this.ResponseStateField.Equals(value) != true)) {
                    this.ResponseStateField = value;
                    this.RaisePropertyChanged("ResponseState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public TrackerApp.Website.TimelogSecurity.APIMessage[] Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfSecurityToken", Namespace="http://www.timelog.com/api/tlp/v1_1")]
    [System.SerializableAttribute()]
    public partial class ResponseOfSecurityToken : TrackerApp.Website.TimelogSecurity.APIBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TrackerApp.Website.TimelogSecurity.SecurityToken[] ReturnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnTypeDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TrackerApp.Website.TimelogSecurity.Request RequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TrackerApp.Website.TimelogSecurity.ExecutionStatus ResponseStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TrackerApp.Website.TimelogSecurity.APIMessage[] MessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackerApp.Website.TimelogSecurity.SecurityToken[] Return {
            get {
                return this.ReturnField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnField, value) != true)) {
                    this.ReturnField = value;
                    this.RaisePropertyChanged("Return");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnTypeDescription {
            get {
                return this.ReturnTypeDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnTypeDescriptionField, value) != true)) {
                    this.ReturnTypeDescriptionField = value;
                    this.RaisePropertyChanged("ReturnTypeDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public TrackerApp.Website.TimelogSecurity.Request Request {
            get {
                return this.RequestField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestField, value) != true)) {
                    this.RequestField = value;
                    this.RaisePropertyChanged("Request");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public TrackerApp.Website.TimelogSecurity.ExecutionStatus ResponseState {
            get {
                return this.ResponseStateField;
            }
            set {
                if ((this.ResponseStateField.Equals(value) != true)) {
                    this.ResponseStateField = value;
                    this.RaisePropertyChanged("ResponseState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public TrackerApp.Website.TimelogSecurity.APIMessage[] Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExecutionStatus", Namespace="http://schemas.datacontract.org/2004/07/TimeLog.TLP.Common")]
    public enum ExecutionStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSet = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invalid = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APIMessage", Namespace="http://www.timelog.com/api/tlp/v1_1")]
    [System.SerializableAttribute()]
    public partial class APIMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TrackerApp.Website.TimelogSecurity.APIMessageSeverity SeverityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackerApp.Website.TimelogSecurity.APIMessageSeverity Severity {
            get {
                return this.SeverityField;
            }
            set {
                if ((this.SeverityField.Equals(value) != true)) {
                    this.SeverityField = value;
                    this.RaisePropertyChanged("Severity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Role", Namespace="http://schemas.datacontract.org/2004/07/TimeLog.TLP.Security")]
    public enum Role : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExternalContractor = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExternalSalesperson = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TeamLeader = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProjectMember = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SalesPerson = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProjectManager = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LimitedSectionManager = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SectionManager = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Manager = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SystemAdministrator = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserCRM = 41,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserHelpDesk = 42,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserSalary = 43,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProjectManagement = 44,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CustomerContacts = 45,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TimeTracking = 46,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserCanCreateProject = 47,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserCanEditOwnProjects = 48,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserCanEditAllProjects = 49,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserCanEditOwnDepartmentProjects = 50,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CanBeAllocated = 51,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestParameter", Namespace="http://www.timelog.com/api/tlp/v1_1")]
    [System.SerializableAttribute()]
    public partial class RequestParameter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APIMessageSeverity", Namespace="http://schemas.datacontract.org/2004/07/TimeLog.TLP.API.Proxy.Communication.V1_0")]
    public enum APIMessageSeverity : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invalid = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Message = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.timelog.com/api/tlp/v1_2", ConfigurationName="TimelogSecurity.SecurityService")]
    public interface SecurityService {
        
        [System.ServiceModel.OperationContractAttribute(Action="IsAliveRequest", ReplyAction="IsAliveReponse")]
        bool IsAlive();
        
        [System.ServiceModel.OperationContractAttribute(Action="IsAliveRequest", ReplyAction="IsAliveReponse")]
        System.Threading.Tasks.Task<bool> IsAliveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="GetTokenRequest", ReplyAction="GetTokenReponse")]
        TrackerApp.Website.TimelogSecurity.ResponseOfSecurityToken GetToken(string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetTokenRequest", ReplyAction="GetTokenReponse")]
        System.Threading.Tasks.Task<TrackerApp.Website.TimelogSecurity.ResponseOfSecurityToken> GetTokenAsync(string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetTimeRegistrationSettingsRequest", ReplyAction="GetTimeRegistrationSettingsReponse")]
        TrackerApp.Website.TimelogSecurity.ResponseOfTimeRegistrationSettings GetTimeRegistrationSettings(TrackerApp.Website.TimelogSecurity.SecurityToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetTimeRegistrationSettingsRequest", ReplyAction="GetTimeRegistrationSettingsReponse")]
        System.Threading.Tasks.Task<TrackerApp.Website.TimelogSecurity.ResponseOfTimeRegistrationSettings> GetTimeRegistrationSettingsAsync(TrackerApp.Website.TimelogSecurity.SecurityToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetUserRequest", ReplyAction="GetUserReponse")]
        TrackerApp.Website.TimelogSecurity.ResponseOfUser GetUser(TrackerApp.Website.TimelogSecurity.SecurityToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetUserRequest", ReplyAction="GetUserReponse")]
        System.Threading.Tasks.Task<TrackerApp.Website.TimelogSecurity.ResponseOfUser> GetUserAsync(TrackerApp.Website.TimelogSecurity.SecurityToken token);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SecurityServiceChannel : TrackerApp.Website.TimelogSecurity.SecurityService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SecurityServiceClient : System.ServiceModel.ClientBase<TrackerApp.Website.TimelogSecurity.SecurityService>, TrackerApp.Website.TimelogSecurity.SecurityService {
        
        public SecurityServiceClient() {
        }
        
        public SecurityServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SecurityServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecurityServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecurityServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool IsAlive() {
            return base.Channel.IsAlive();
        }
        
        public System.Threading.Tasks.Task<bool> IsAliveAsync() {
            return base.Channel.IsAliveAsync();
        }
        
        public TrackerApp.Website.TimelogSecurity.ResponseOfSecurityToken GetToken(string user, string password) {
            return base.Channel.GetToken(user, password);
        }
        
        public System.Threading.Tasks.Task<TrackerApp.Website.TimelogSecurity.ResponseOfSecurityToken> GetTokenAsync(string user, string password) {
            return base.Channel.GetTokenAsync(user, password);
        }
        
        public TrackerApp.Website.TimelogSecurity.ResponseOfTimeRegistrationSettings GetTimeRegistrationSettings(TrackerApp.Website.TimelogSecurity.SecurityToken token) {
            return base.Channel.GetTimeRegistrationSettings(token);
        }
        
        public System.Threading.Tasks.Task<TrackerApp.Website.TimelogSecurity.ResponseOfTimeRegistrationSettings> GetTimeRegistrationSettingsAsync(TrackerApp.Website.TimelogSecurity.SecurityToken token) {
            return base.Channel.GetTimeRegistrationSettingsAsync(token);
        }
        
        public TrackerApp.Website.TimelogSecurity.ResponseOfUser GetUser(TrackerApp.Website.TimelogSecurity.SecurityToken token) {
            return base.Channel.GetUser(token);
        }
        
        public System.Threading.Tasks.Task<TrackerApp.Website.TimelogSecurity.ResponseOfUser> GetUserAsync(TrackerApp.Website.TimelogSecurity.SecurityToken token) {
            return base.Channel.GetUserAsync(token);
        }
    }
}
